name: Deploy to Hostinger via FTP
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: Build & FTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 2
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install Dependencies
        run: |
          rm -f package-lock.json
          npm install
        
      - name: Build Project
        run: npm run build
        
      - name: FTP Deployment
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.LEGWRK_FTP_HOST }}
          username: ${{ secrets.LEGWRK_FTP_USER }}
          password: ${{ secrets.LEGWRK_FTP_PASSWORD }}
          server-dir: ${{ secrets.LEGWRK_FTP_DIR }}/
          local-dir: ./dist/
